// Signals, blending constants, and helpers shared by every platform.
//
// Design rules (from https://docs.typesafe.ai — see `Question design` in the README):
//  - one atomic judgment per question; combine in code
//  - phrase so a high noul means "this signal is PRESENT" (bad = true)
//  - literal wording; put boundary cases in criteria; keep counting/arithmetic in code
//  - all questions for one post go in ONE request (speculative fan-out is ~free)
//  - one post per request: items in a shared state contaminate each other
//
// What lives here is what is genuinely identical across X and LinkedIn. Anything whose
// wording has to change lives in the platform module, even when the idea is similar —
// jev-1.13 reads literally, so "a thread" and "the carousel in the comments" are not
// interchangeable just because both mean "withheld value".

import type { ChoiceQuestion, EntryType, NoulQuestion, Platform } from "../types.ts";

export interface Signal {
  /**
   * How damning this signal is at full confidence. The composite is driven by the WORST
   * single signal, not an average, so a weight of 1.0 means "certain of this alone is
   * certainly slop" and 0.3 means "this alone can never hide a post".
   */
  weight: number;
  question: NoulQuestion;
}

export type SignalSet = Record<string, Signal>;

/**
 * A Noul with explicit criteria on both sides.
 *
 * `yes`/`no` are EntryType, not string: the API accepts an object or array there, which
 * is how a `what` + `examples` shape pins down a subtle boundary.
 * See https://docs.typesafe.ai/primitives/advanced
 */
export function noul(instructions: NoulQuestion["instructions"], yes: EntryType, no: EntryType): NoulQuestion {
  return { type: "noul", instructions, criteria: { true: yes, false: no } };
}

// ---------------------------------------------------------------------------
// Signals both platforms share
// ---------------------------------------------------------------------------

export const CORE_SIGNALS: SignalSet = {
  engagement_bait: {
    weight: 1.0,
    question: noul(
      {
        question:
          "Does `post.text` ask readers to like, comment, repost, share, reply, follow, bookmark, or tag someone, mainly to drive engagement?",
        focus:
          "Look for a request aimed at the reader's action on the platform. A genuine question the author plausibly wants answered is NOT engagement bait.",
      },
      "Asks for a like/comment/repost/share/reply/follow/bookmark/tag, or uses a reply-farming prompt such as 'Agree?', 'Thoughts?', 'Who else?', 'Name a better one. I'll wait.', 'Which one are you?'",
      "Makes no such request, or asks a specific question the author plausibly wants a real answer to",
    ),
  },

  ai_prose: {
    weight: 0.9,
    question: noul(
      {
        question:
          "Was `post.text` most likely generated by a language model to farm engagement, rather than written by a person or by an organisation's own communications staff?",
        focus:
          "Style tells only, not subject matter: uniform sentence rhythm, repeated 'It's not X. It's Y.' contrasts, groups of three, 'Let that sink in.', emoji-headed bullet lists, tidy symmetrical structure, and an absence of any idiosyncratic or careless detail. Official product announcements, press copy and marketing from a company account are written to a house style and are NOT what this question is about — polish alone is not evidence.",
      },
      {
        what: "Reads as model-generated filler posted to farm engagement: templated, evenly polished, voiceless, and saying nothing a specific person needed to say",
        examples: [
          "It's not about the tools. It's about the mindset. Most people optimize for output. The best optimize for leverage.",
          "Here's what nobody tells you about AI: 1) It's a tool 2) It's not magic 3) It rewards the prepared",
        ],
      },
      {
        what: "Written by a person, OR official/marketing copy from an organisation about its own product, event or news — even when that copy is polished, formulaic, or full of superlatives",
        examples: [
          "every codebase has one file everyone is scared to touch",
          "Our new GPU is now available through partners worldwide. Learn more at the link.",
          "Odds update: the market has moved 8 points since this morning.",
        ],
      },
    ),
  },

  rage_bait: {
    weight: 0.85,
    question: noul(
      {
        question:
          "Is `post.text` built around a manufactured hot take, outrage, or contrarian claim stated to provoke replies rather than to make a supported argument?",
        focus: "A strong or unpopular opinion WITH reasoning or evidence is not rage bait.",
      },
      "A provocative claim asserted with little reasoning, framed to be argued with: 'Unpopular opinion:', 'X is dead.', 'Nobody wants to admit this but...', deliberate strawmanning of a group",
      "A plain statement, or an opinion supported by reasoning, examples, or evidence",
    ),
  },

  sells_something: {
    weight: 0.9,
    question: noul(
      {
        question:
          "Does `post.text` promote a course, newsletter, cohort, webinar, paid community, coaching, or lead magnet, or ask the reader to DM, reply, or comment a keyword to receive something?",
        focus:
          "Any promotional call to action by the author for their own or their employer's offering. A job opening the reader could apply for, a free release, and an invitation to discuss the post's subject are NOT promotion.",
      },
      "Promotes or sells: 'link in bio', 'my course is open', 'join 40,000 readers', 'comment GUIDE and I'll send it', 'book a call', 'spots left', affiliate pitches",
      "No offer; or the only call to action is a job posting, a free release, an event the author is not selling, or 'DM me with questions' about the post's subject",
    ),
  },

  self_promo: {
    weight: 0.75,
    question: noul(
      {
        question:
          "Is the main purpose of `post.text` to display the author's own achievement, revenue, promotion, award, or milestone?",
        focus:
          "Distinguish from an update that gives the reader something usable — what was done, what broke, what the numbers mean. Framing it as gratitude or humility does not change the purpose.",
      },
      "Exists to show the win: 'Humbled to announce...', 'Grateful to share...', 'just crossed $40k MRR', 'I don't usually post about wins, but...', screenshots of earnings as proof",
      "Not about the author's own success, or reports the achievement alongside what actually produced it and what a reader could take from it",
    ),
  },

  empty_wisdom: {
    weight: 0.9,
    question: noul(
      {
        question:
          "Is `post.text` composed mainly of generic motivational, leadership, or self-improvement statements that could apply to anyone and any situation?",
        focus:
          "The 'discipline is choosing what you want most over what you want now' shape. A specific observation, a joke, or a concrete argument about a real thing is NOT this, even if it is short. A post can mention a real event and still be mostly platitudes.",
      },
      "Generic maxims with little or no specific content: 'consistency beats talent', 'your network is your net worth', 'growth happens outside your comfort zone', 'most people don't fail, they quit'",
      "Mostly specific information, a concrete story with particulars, a joke, a question, or a clearly stated argument",
    ),
  },

  stolen_or_recycled: {
    // Deliberately capped. Measured on X samples it fires 0.73 on a good original
    // one-liner and 0.38 on a plain joke — it reads "familiar-sounding" as "recycled".
    // Kept because it contributes a little to the mean; never allowed to hide alone.
    weight: 0.3,
    question: noul(
      {
        question:
          "Does `post.text` read as recycled content — a well-worn copypasta, a widely-circulated anecdote, or a meme format — presented as the author's own thought?",
        focus:
          "Only judge from the text itself. If you have no reason to think it is recycled, answer no. Explicitly quoting or crediting someone else is NOT this.",
      },
      "A familiar circulating anecdote or template presented as first-hand: the 'a CEO asked me one question in the interview' story, 'my grandfather told me', recognisable copypasta",
      "Reads as the author's own words, or openly quotes/credits a source",
    ),
  },
};

// ---------------------------------------------------------------------------
// The holistic verdict — one Choice asking the whole question at once.
//
// Adapted from jev-slop-guard (https://github.com/davertor/jev-slop-guard), whose entire
// design is this single question, and which uses one question for both platforms.
//
// Measured on 25 labelled X posts against our own 10-Noul battery:
//   holistic P(slop):  good max 0.54 · slop min 0.85 · gap 0.31 · ~560 tok
//   battery composite: good max 0.38 · slop min 0.42 · gap 0.05 · ~2,900 tok
//
// The single relative Choice separated ~6x better at a fifth of the tokens. A Choice
// forces a commitment between two named options; independent Nouls averaged together
// regress to the middle. So the Choice leads and the battery corroborates — and the
// battery earns its keep by being the only thing that can say WHICH signal fired.
// ---------------------------------------------------------------------------

export const VERDICT_CHOICE: ChoiceQuestion = {
  type: "choice",
  instructions: {
    question: "Is `post.text` low-value slop?",
    focus:
      "Judge the writing and the intent, not the topic. Prefer not_slop when the post adds something specific, or when you cannot tell who wrote it or why. `post.platform` says which network it came from; judge it by that network's normal conventions.",
  },
  criteria: {
    slop: {
      what: "Noise, clickbait, or empty daily content posted for reach rather than to say something",
      includes: [
        "engagement bait; rage or curiosity hooks with no payoff",
        "templated or model-generic hustle, motivation, or 'wisdom'",
        "claimed expertise with no specifics behind it",
        "polished prose carrying no lived detail and no new information",
        "mainly selling, hard promo, or funnel copy",
        "personal-brand flex with nothing new in it",
        "riding a trending topic without adding to it",
      ],
    },
    not_slop: {
      what: "Brings something real, or its nature is genuinely unclear",
      includes: [
        "concrete detail, a personal take, a genuine question",
        "humour with specificity; technical substance; news with substance",
        "an organisation's own announcement, product news, or data update — even when the copy is polished and formulaic",
        "a post whose text is a caption for attached media or a link",
        "a job posting, an event listing, or a free release",
        "anything where authorship or intent is simply unclear",
      ],
    },
  },
};

// ---------------------------------------------------------------------------
// Per-user topic questions. Speculative fan-out: these ride along in the same request.
// ---------------------------------------------------------------------------

export function interestQuestions(interests: string[]): Record<string, NoulQuestion> {
  const out: Record<string, NoulQuestion> = {};
  interests.forEach((topic, i) => {
    out[`interest_${i}`] = noul(
      {
        topic,
        question: "Is `post.text` substantively about the subject named in `topic`?",
        focus: "The post must actually discuss or inform about the subject, not merely mention a related word.",
      },
      "The post's main content is about this subject, or a large part of it is",
      "The subject is absent, or only mentioned in passing",
    );
  });
  return out;
}

export function excludedTopicQuestions(topics: string[]): Record<string, NoulQuestion> {
  const out: Record<string, NoulQuestion> = {};
  topics.forEach((topic, i) => {
    out[`excluded_${i}`] = noul(
      {
        topic,
        question: "Is `post.text` primarily about, or primarily expressing, the thing described in `topic`?",
        focus:
          "Judge the post's main thrust. Read `topic` literally: if it names an attitude (e.g. 'hostility toward AI'), match posts expressing that attitude, not posts about the subject generally.",
      },
      "The post's main thrust matches `topic`",
      "The post is about something else, or touches `topic` only incidentally",
    );
  });
  return out;
}

// ---------------------------------------------------------------------------
// Code-side structural features, 0..1.
//
// CORROBORATE, NEVER DECIDE.
//
// Every one of these is a formatting convention, and formatting conventions are shared by
// slop merchants and by people with something to say. Measured on a live X timeline,
// twice: an industrial-automation post was hidden on hashtag_spam=1.00 alone, and a NASA
// thread was collapsed on thread_marker=1.00 alone. Both were correct detections of the
// format and wrong judgements of the post.
//
// The weights are all low enough that no structural feature can cross a hide threshold on
// its own. They only push a post a real signal has already implicated.
//
// Counting also belongs here rather than in a question: jev-1.13 does not count reliably,
// and a regex does it exactly and for free.
// ---------------------------------------------------------------------------

export const STRUCTURAL_WEIGHTS: Record<Platform, Record<string, number>> = {
  x: {
    thread_marker: 0.35, // "🧵", "1/12", "(1/n)"
    emoji_bullets: 0.3,
    staccato: 0.3,
    hashtag_spam: 0.2,
  },
  linkedin: {
    // "Broetry" — one short line per sentence — is a much stronger tell on LinkedIn than
    // the same shape is on X, where short posts are simply normal.
    staccato: 0.45,
    emoji_bullets: 0.35,
    hashtag_spam: 0.2,
  },
};

const THREAD_MARKER = /(\u{1F9F5})|(^|\s)\(?\d{1,2}\s*\/\s*(\d{1,2}|n)\)?(\s|$)/u;
const LEADING_EMOJI =
  /^\s*(?:[\u{1F300}-\u{1FAFF}\u{2190}-\u{21FF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}\u{FE0F}\u{2022}\u{25AA}\u{25CF}\u{27A4}]|[-*\u2013\u2014]|\d{1,2}[.)])\s+/u;

export function structuralSignals(text: string, platform: Platform): Record<string, number> {
  const lines = text
    .split(/\n+/)
    .map((l) => l.trim())
    .filter(Boolean);

  const bulleted = lines.filter((l) => LEADING_EMOJI.test(l)).length;
  const emoji_bullets = lines.length >= 3 ? ramp(bulleted / lines.length, 0.4, 0.8) : 0;

  let staccato = 0;
  if (lines.length >= 5) {
    const short = lines.filter((l) => l.length <= 60).length;
    staccato = ramp(short / lines.length, 0.6, 0.95);
  }

  const tags = (text.match(/(^|\s)#[A-Za-z0-9_]{2,}/g) ?? []).length;
  const hashtag_spam = ramp(tags, 2, 6);

  const out: Record<string, number> = { emoji_bullets, staccato, hashtag_spam };
  if (platform === "x") out.thread_marker = THREAD_MARKER.test(text) ? 1 : 0;
  return out;
}

/** 0 at or below `lo`, 1 at or above `hi`, linear between. */
function ramp(v: number, lo: number, hi: number): number {
  if (hi <= lo) return v > lo ? 1 : 0;
  return Math.max(0, Math.min(1, (v - lo) / (hi - lo)));
}

// ---------------------------------------------------------------------------
// Blending constants
// ---------------------------------------------------------------------------

/**
 * How the battery's three contributions combine into its own composite.
 *
 *   WORST  the single most damning signal (or structural feature). Dominant on purpose:
 *          a slop post usually trips ONE pattern hard. Measured on X, a rage-bait post
 *          scored rage_bait 0.96 with every other signal ~0.02, and the mean came out
 *          0.19 — indistinguishable from a good post.
 *   MEAN   broad slop character, for posts mildly bad in many ways at once.
 *   EMPTY  1 - substance. A nudge, not a verdict.
 *
 * EMPTY_MEDIA_DAMPING: on a post carrying media or a link, thin text is EXPECTED — the
 * content is the video or the article and the text is a caption. Measured on a live
 * timeline: a legitimate industrial-automation post scored substance 0.14 purely because
 * its text was a headline above a video.
 */
export const BLEND = { worst: 0.65, mean: 0.2, empty: 0.15 } as const;
export const EMPTY_MEDIA_DAMPING = 0.4;

/** How much the holistic Choice is worth against the whole battery. See VERDICT_CHOICE. */
export const VERDICT_BLEND = 0.6;

/**
 * The hard-signal rule ("any one of these disqualifies on its own") is not allowed to fire
 * when the holistic Choice confidently disagrees.
 *
 * The rule predates the holistic question and was written when the battery composite was
 * the only score. Measured on a live LinkedIn feed it hid a post at a composite of 0.30 —
 * far below the 0.64 hide threshold — purely because `engagement_bait` read 0.96, while
 * the holistic Choice said P(slop) = 0.06. That is a genuine call for help or a real
 * question that happens to be phrased like bait.
 *
 * One strong signal is still enough to hide a post, but not over a confident objection
 * from the better-separated judgment. Below this floor the composite decides on its own.
 */
export const HARD_SIGNAL_HOLISTIC_FLOOR = 0.35;
